site_name: Mike Knapp's Homepage
nav:
  - Home: index.md
  - Principles: principles.md
  - Programming: programming.md
  - Algorithms: algorithms.md
  - Command Line: commandline.md
  - Data: data.md
  - Formats: formats.md 
  - Web: web.md
  - Operating System: operatingsystem.md
  - IDE: ide.md
  - Documentation: documentation.md
  - Cloud: cloud.md
  - Streaming: streaming.md
  - Infrastructure as Code: iac.md
  - Containers: containers.md
  - Networking: networking.md
  - CICD: cicd.md
  - Monitoring: monitoring.md
  - Security: security.md
  - Machine Learning: machinelearning.md
  - Grammar: grammar.md
theme: readthedocs